

const getRecords = async (req,res) => {
    try {
        
    } catch (error) {
        
    }

}